# Generated by Django 4.1.2 on 2022-10-26 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userextend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userextend',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
