# Generated by Django 4.1.2 on 2022-11-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0002_userextend_active_userextend_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='image',
            field=models.ImageField(blank=True, default='profile/user-default.png', null=True, upload_to='profile/'),
        ),
    ]
