# Generated by Django 4.1.2 on 2022-10-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='asigned_to',
            new_name='assigned_to',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_textbox',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
