# Generated by Django 4.1.2 on 2022-11-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0003_userextend_image'),
        ('tasks', '0002_rename_asigned_to_tasks_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_textbox',
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=1000, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userextend.userextend')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasks')),
            ],
        ),
    ]
