# Generated by Django 4.1.2 on 2022-11-12 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_tasks_task_textbox_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
