# Generated by Django 4.1.2 on 2022-11-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskcomment_created_at_taskcomment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='updated_at',
        ),
    ]
